<ips:template parameters="$events, $today, $attack, $defense, $orientation='vertical'" />
<h3 class='ipsType_reset ipsWidget_title'>{lang="avacalendar_widget_avaevent_title"}</h3>
<div class='ipsWidget_inner'>
	{{if $orientation == 'vertical'}}
		<div class='ipsPad_half'>
	{{endif}}
	{{if !empty( $events ) }}
		{{foreach $events as $event}}
			{{if !isset( $today_display ) && $event->nextOccurrence( $today, 'startDate' )->mday == $today->mday}}
				{{$today_display = TRUE;}}
				<h2 class='ipsType_sectionHead'>{lang="avacalendar_widget_avaevent_today"}</h2>
				<hr class='ipsHr'>
				<div class='ipsGrid ipsSpacer_bottom ipsSpacer_double'>
			{{elseif !isset( $tomorrow_display ) && $event->nextOccurrence( $today, 'startDate' )->mday == $today->adjust( '1 day' )->mday}}
				{{$tomorrow_display = TRUE;}}
				{{if $today_display}}
					</div>
				{{endif}}
				<h2 class='ipsType_sectionHead'>{lang="avacalendar_widget_avaevent_tomorrow"}</h2>
				<hr class='ipsHr'>
				<div class='ipsGrid ipsSpacer_bottom ipsSpacer_double'>
			{{elseif !isset($otherday_display) && $event->nextOccurrence( $today, 'startDate' )->mday >= $today->adjust( '2 days' )->mday && $event->nextOccurrence( $today, 'startDate' )->mon == $today->adjust( '2 days' )->mon}}
				{{$otherday_display = TRUE;}}
				{{if $tomorrow_display}}
					</div>
				{{endif}}
				<h2 class='ipsType_sectionHead'>{lang="avacalendar_widget_avaevent_otherday"}</h2>
				<hr class='ipsHr'>
				<div class='ipsGrid ipsSpacer_bottom ipsSpacer_double'>
			{{endif}}

			<div class='ipsGrid_span4'>
				<h3>
					{{if $event->calendar_id == $defense}}
						<span class='ipsBadge ipsBadge_intermediary ipsBadge_icon' data-ipsTooltip title='{lang="avacalendar_widget_avaevent_defense"}'>
							<i class='fa fa-shield'></i>
						</span>
					{{else}}
						<span class='ipsBadge ipsBadge_warning ipsBadge_icon' data-ipsTooltip title='{lang="avacalendar_widget_avaevent_attack"}'>
							<i class='fa fa-bolt'></i>
						</span>
					{{endif}}

					{$event->title}
				</h3>

				{{$interval = $event->nextOccurrence( $today, 'startDate' )->diff( $today );}}

				{{if !is_null($event->ava_won) || $event->nextOccurrence( $today, 'endDate' ) < $today}}
					{{if !is_null($event->ava_won)}}
						{{if $event->ava_won}}
							<span class='ipsBadge ipsBadge_positive'>
								{lang="avacalendar_widget_avaevent_ava_won"}
							</span>
						{{else}}
							<span class='ipsBadge ipsBadge_negative'>
								{lang="avacalendar_widget_avaevent_ava_lost"}
							</span>
						{{endif}}
					{{else}}
						<span class='ipsBadge ipsBadge_new ipsBadge_medium'>
							{lang="avacalendar_widget_avaevent_ended"}
						</span>
					{{endif}}
				{{elseif $event->nextOccurrence( $today, 'startDate' ) < $today}}
					<span class='ipsBadge ipsBadge_positive ipsBadge_medium'>
						{lang="avacalendar_widget_avaevent_in_progress"}
					</span>
				{{elseif $interval->d == 0 && $interval->h == 0 && $interval->i <= 30}}
					<span class='ipsBadge ipsBadge_negative ipsBadge_medium' data-ipsTooltip title='{lang="avacalendar_widget_avaevent_30minutes" pluralize="$interval->i"}'>
						{lang="avacalendar_widget_avaevent_will_start"}
					</span>
				{{else}}
					<span class='ipsBadge ipsBadge_neutral ipsBadge_medium'>
						{{if $otherday_display}}
							{$event->nextOccurrence( $today, 'startDate' )->calendarDate()} - 
						{{endif}}
							
						{$event->nextOccurrence( $today, 'startDate' )->localeTime( FALSE )}
					</span>

					<span class='ipsType_light'>
						{{if $event->ava_meeting}}
							<i class='fa fa-clock-o' data-ipsTooltip title='{lang="avacalendar_widget_avaevent_meeting_hour"}'></i> {$event->ava_meeting}
						{{endif}}

						{{if $event->ava_position}}
							{{if $event->ava_meeting}}
								-
							{{endif}}
							<i class='fa fa-map-marker' data-ipsTooltip title='{lang="avacalendar_widget_avaevent_meeting_pos"}'></i> {$event->ava_position}
						{{endif}}
					</span>
				{{endif}}
			</div>
		{{endforeach}}
		{{if $today_display || $tomorrow_display || $otherday_display}}
			</div>
		{{else}}
			<b>Aucun AvA prévu</b>
		{{endif}}
	{{else}}
		<div class='ipsType_light ipsPad_half ipsType_center'>{lang="no_upcoming_events"}</div>
	{{endif}}
	{{if $orientation == 'vertical'}}
		</div>
	{{endif}}
</div>